apiVersion: v1
kind: Service
metadata:
  name: surdej-frontend
  namespace: surdej
  labels:
    app: surdej-frontend
spec:
  type: ClusterIP
  selector:
    app: surdej-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
