/**
 * Domain Manifest
 *
 * Defines the contract for a domain module. Domains are the primary
 * unit of business logic in Surdej — each domain provides commands,
 * pages, topologies, and other capabilities.
 *
 * Domain manifests are discovered by the Vite plugin at build time
 * and merged into a registry available at runtime.
 *
 * @module domains
 */

/** A domain manifest — one per domain folder */
export interface DomainManifest {
    /** Unique domain identifier (kebab-case) */
    id: string;

    /** Human-readable name */
    name: string;

    /** Short description of this domain */
    description?: string;

    /** Lucide icon name */
    icon?: string;

    /** Domain version (semver) */
    version?: string;

    /** Command IDs this domain registers */
    commands?: string[];

    /** Route paths this domain adds */
    routes?: DomainRoute[];

    /** Topology definitions this domain provides */
    topologies?: DomainTopologyRef[];

    /** Feature flags this domain depends on */
    requiredFeatures?: string[];

    /** Other domains this domain depends on */
    dependencies?: string[];
}

/** A route contributed by a domain */
export interface DomainRoute {
    /** Route path (relative to root) */
    path: string;

    /** Route label for breadcrumbs */
    label: string;

    /** Command ID for navigation */
    commandId?: string;
}

/** Reference to a topology provided by a domain */
export interface DomainTopologyRef {
    /** Topology ID (matches TopologyDefinition.id) */
    id: string;

    /** Path to the topology definition file (relative to domain root) */
    file: string;

    /** Whether it's auto-generated vs hand-written */
    generated?: boolean;
}

/** The build-time domain registry (generated by Vite plugin) */
export interface DomainRegistry {
    /** All discovered domains */
    domains: DomainManifest[];

    /** Timestamp when the registry was generated */
    generatedAt: string;

    /** Number of domains found */
    count: number;
}

/**
 * Validate a domain manifest for required fields.
 */
export function validateDomainManifest(manifest: unknown): string[] {
    const errors: string[] = [];

    if (!manifest || typeof manifest !== 'object') {
        return ['Manifest must be a non-null object'];
    }

    const m = manifest as Record<string, unknown>;

    if (!m.id || typeof m.id !== 'string') {
        errors.push('Missing required field: id (string)');
    } else if (!/^[a-z][a-z0-9-]*$/.test(m.id)) {
        errors.push(`Invalid id format: "${m.id}" — must be kebab-case`);
    }

    if (!m.name || typeof m.name !== 'string') {
        errors.push('Missing required field: name (string)');
    }

    if (m.commands && !Array.isArray(m.commands)) {
        errors.push('commands must be an array of strings');
    }

    if (m.routes && !Array.isArray(m.routes)) {
        errors.push('routes must be an array');
    }

    if (m.topologies && !Array.isArray(m.topologies)) {
        errors.push('topologies must be an array');
    }

    if (m.requiredFeatures && !Array.isArray(m.requiredFeatures)) {
        errors.push('requiredFeatures must be an array');
    }

    if (m.dependencies && !Array.isArray(m.dependencies)) {
        errors.push('dependencies must be an array');
    }

    return errors;
}
